#!/system/bin/sh

echo "2048" > /sys/devices/virtual/bdi/0:17/read_ahead_kb

echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb

echo "2048" > /sys/devices/virtual/bdi/179:32/read_ahead_kb

echo "2048" > /sys/devices/virtual/bdi/253:0/read_ahead_kb

echo "2048" > /sys/devices/virtual/bdi/7:0/read_ahead_kb

echo "2048" > /sys/devices/virtual/bdi/7:1/read_ahead_kb

echo "2048" > /sys/devices/virtual/bdi/7:2/read_ahead_kb

echo "2048" > /sys/devices/virtual/bdi/7:3/read_ahead_kb

echo "2048" > /sys/devices/virtual/bdi/7:4/read_ahead_kb

echo "2048" > /sys/devices/virtual/bdi/7:5/read_ahead_kb

echo "2048" > /sys/devices/virtual/bdi/7:6/read_ahead_kb

echo "2048" > /sys/devices/virtual/bdi/7:7/read_ahead_kb

echo "2048" > /sys/devices/virtual/bdi/default/read_ahead_kb

echo "2048" > /sys/devices/virtual/bdi/mtd-romap/read_ahead_kb

echo "2048" > /sys/devices/virtual/bdi/mtd-rwmap/read_ahead_kb

echo "2048" > /sys/devices/virtual/bdi/mtd-unmap/read_ahead_kb

##SD Card Read Speed Cache Increased to 2mb##